### ISSUE TITLE
Save `env-kwargs` when some are passed

### ISSUE THREAD

**Issue by araffin** [DLR-RM/rl-baselines3-zoo#11]
maybe save the seed to? (need to double check that)

**Comment by SammyRamone** [comment]
I think saving the seed would be a good idea.
Do you have a preference where to save this data? Should it be included to the config yaml that currently saves the hyperparameters, or should it be in an extra file?
I would be willing to implement it and do a PR, since I would like to have this feature too.

**Comment by araffin** [comment]
> should it be in an extra file?

I would say extra file for the env hyperparameters
