### ISSUE TITLE
[question] "Tuned": what is your criterion?

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#185]
Hi,

For all the algorithm/environments, you distinguish the hyperparameters that are tuned (`# Tuned`), and those that must be tuned (`# To be tuned`). What is your criterion for considering hyperparameters to be tuned? 

I assume you use 
```bash
python train.py --algo <ALGO> --env <ENV> -optimize
```
but with how many trials? what is your pruner? your sampler?

**Comment by araffin** [comment]
Hello,

>What is your criterion for considering hyperparameters to be tuned?

The criterion is a bit subjective but the main ideas being my reasoning are:
- tuned hyperparameters are hyperparameters that allow to reach good performance most of the time (where "good" is task dependent and a bit subjective, and "most of the time" is something like more than 75% of the time)

For some of the hyperparameters, I actually ran automated hyperparameter tuning (and adapted some manually afterward), for others, values are from original papers or other codebases (OpenAI Baselines).

> but with how many trials? what is your pruner? your sampler?

my default setting is 500 trials (but usually I stop the optimization early or most of the runs get pruned at some point) with tpe sampler (you can activate the multivariate option) and the median pruner.
I also found it useful to train on a fraction of the full budget (for instance on 5e5 steps if you want to train on 1M steps at the end) in order to save a lot of computation time.

Last but not least, take a look at the hyperparameter optimization parameter and uncomment the ones related to HER if you want to optimize for this algorithm.
(you will be interested by this PR btw: https://github.com/DLR-RM/stable-baselines3/pull/654)

Answering the additional questions from your mail:

> With the same set of hyperparameters, one can obtain agents with very variable performances (I am not talking about the variability on the evaluation of an agent, but the variability on the performances of the obtained agents). Currently, in your code, a set of hyperparameters is evaluated after a single training. To solve this weakness, you would have to take the median over several trainings (at the cost of a significant increase in optimization time, yes). Have you already thought about this?

See discussion in https://github.com/DLR-RM/rl-baselines3-zoo/issues/151
also: related: https://github.com/DLR-RM/rl-baselines3-zoo/issues/114
