### ISSUE TITLE
RL Zoo CLI

### ISSUE THREAD

**Issue by araffin** [DLR-RM/rl-baselines3-zoo#191]
It would be nice to have a cli that is available everywhere (with completion too), something like:
```bash
sb3 train --algo ppo --env CartPole-v1  
sb3 train --algo ppo --env CartPole-v1  -i custom_params.yaml # allow overwriting hyperparams file with a custom one
sb3 enjoy --algo sac --env Pendulum-v0
sb3 plot_train -a a2c -e Breakout
sb3 plot_eval ...
sb3 plot_from_file
```

**Comment by kachayev** [comment]
Hey @araffin! I've recently done simple `console_scripts` entry point for the package (to help running scripts from folders with custom code). I can polish it and submit PR.  It seems like entry point is the most reliable way for this to work on different platforms. Though a few caveats:

* "everywhere" is typically not desirable because of dependencies management. `console_scripts` could work globally if the package was installed globally. But I assume in most cases packages are installed into virtual environment, and in this case `sb3` would be available only within active env.
* Completion is somewhat complicated functionality to get reliable on multiple platforms/terminals. Usually requires update for terminal init files (like `~/.bash_profile` and so on). But I can check what is a common approach for doing it nowadays.

**Comment by araffin** [comment]
Hello,
thanks for the proposal =)

>  and in this case sb3 would be available only within active env.

yes, that's what I meant by "everywhere"  (more in the sense "from every folder rather than from every env")

> Completion is somewhat complicated functionality to get reliable on multiple platforms/terminals

that's true, but I had in mind to provide only minimal completion (different first level command), at least for bash/zsh users.
I did that in the past for a wrapper around conan that tries to mimic conda env.

> I've recently done simple console_scripts entry point for the package 

You can submit a draft PR yes, but I'm not sure what you mean exactly by "console scripts".
(I also have private code of a cli I created for another purpose (but not for the zoo))

**Comment by kachayev** [comment]
`console_scripts` is one the functionality `setuptools` provides for automatically generating script wrappers for modules within the packages, link to their [docs](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points).
