### ISSUE TITLE
What does the t in the csv file trained by the sb3 library mean?

### ISSUE THREAD

**Issue by learningxiaobai** [DLR-RM/rl-baselines3-zoo#248]
hello， I have some question？
1. What does the t in the CSV file trained by the sb3 library mean?
![1652952754(1)](https://user-images.githubusercontent.com/68008102/169262133-bd5652fb-6965-4073-93b8-8a8ec33023dc.png)
2. How can I find the success rate data where I have trained ,so that I can plot by myself,thanks.

**Comment by araffin** [comment]
Hello,
before answering, what do you think r, l and t means in the context of RL ?

**Comment by learningxiaobai** [comment]
> Hello, before answering, what do you think r, l and t means in the context of RL ?

r-reward,l-step length,t-time？i am not sure？

**Comment by araffin** [comment]
> r-reward,l-step length,t-time？i am not sure？

Exactly. Those are computed in the `Monitor` wrapper (https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/monitor.py)

Each quantity is per episode (one line is one episode).

r: reward, or more specifically cumulative reward for one episode (aka return)
l: length of the episode
t: time since `t_start` at the end of an episode (wall clock time)

> How can I find the success rate data where I have trained ,so that I can plot by myself,thanks.

You already have the answer in #247 , I will complement there for the `EvalCallback`.
