### ISSUE TITLE
[Question] Number of parallel environments with hyperparameters optimization

### ISSUE THREAD

**Issue by suargi** [DLR-RM/rl-baselines3-zoo#446]
### ❓ Question

Why is the number of parallel environments (n_envs) set to one when using the optimize-hyperparameters? https://github.com/DLR-RM/rl-baselines3-zoo/blob/e06914e9835b8f3233b18d59943b1464b89ddb90/rl_zoo3/exp_manager.py#L198

Thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Because they are not created here, but there:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/e06914e9835b8f3233b18d59943b1464b89ddb90/rl_zoo3/exp_manager.py#L743

See comment just above:
Why is the number of parallel environments (n_envs) set to one when using the optimize-hyperparameters? https://github.com/DLR-RM/rl-baselines3-zoo/blob/e06914e9835b8f3233b18d59943b1464b89ddb90/rl_zoo3/exp_manager.py#L197
