### ISSUE TITLE
[question] Why hyperparameters search don't use `--eval-freq` argument? 

### ISSUE THREAD

**Issue by caburu** [DLR-RM/rl-baselines3-zoo#59]
When we train an agent we need to use `--eval-freq` argument to configure the evaluation process.

But when we do hyperparameters search `--eval-freq` is ignored and `--n-evaluations` is used instead. So evaluation frequency is indirectly calculated (`n_timesteps / n_evaluations`).

I think it would be simpler if we could use only `--eval-freq` argument. Is there any special reason to keep both arguments?

**Comment by araffin** [comment]
Hello,

>I think it would be simpler if we could use only --eval-freq argument. Is there any special reason to keep both arguments?

I would say mainly historic reason and also to decouple the two.
`eval-freq` came after (in SB2 zoo) the hyperparameter tuning and is used for periodic evaluation during training.

The `n_timesteps / n_evaluations` is a heuristic to avoid calling evaluation too many times (slowing down the hyperparameter optimization) also because the tuning is done with a smaller budget (smaller `n_timesteps` compared to full training).
I'm also using that as it is easier to reason with percentage of budget for the pruner (see MedianPruner example).

but you are probably right, we could merge the two, I'm just afraid to add some confusion.

**Comment by caburu** [comment]
Ok, thanks for the reply. I was afraid to be missing something.
